apiVersion: batch/v1
kind: Job
metadata:
  name: gitinitjob
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: gitinitjob
    spec:
      containers:
      - name: gitinitjob
        image: akubicharm/centos-git
        command: ["/workspace/run.sh"]
      restartPolicy: Never
