apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Red Hat OpenJDK 8
  name: redhat-openjdk18-openshift
spec:
  dockerImageRepository: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
  tags:
  - annotations:
      description: Build and run Java applications using Maven and OpenJDK 8.
      iconClass: icon-jboss
      openshift.io/display-name: Red Hat OpenJDK 8
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:8,xpaas:1.0
      tags: builder,java,xpaas,openjdk
      version: "1.0"
    generation: 1
    importPolicy: {}
    name: "1.0"
    referencePolicy:
      type: Source
  - annotations:
      description: Build and run Java applications using Maven and OpenJDK 8.
      iconClass: icon-jboss
      openshift.io/display-name: Red Hat OpenJDK 8
      sampleContextDir: undertow-servlet
      sampleRepo: https://github.com/jboss-openshift/openshift-quickstarts
      supports: java:8,xpaas:1.4
      tags: builder,java,xpaas,openjdk
      version: "1.1"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.1
    generation: 2
    importPolicy: {}
    name: "1.1"
    referencePolicy:
      type: Source
  - annotations: null
    from:
      kind: DockerImage
      name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.1-10
    generation: 2
    importPolicy: {}
    name: 1.1-10
    referencePolicy:
      type: Source
  - annotations: null
    from:
      kind: DockerImage
      name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.1-11
    generation: 2
    importPolicy: {}
    name: 1.1-11
    referencePolicy:
      type: Source
  - annotations: null
    from:
      kind: DockerImage
      name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.1-8
    generation: 2
    importPolicy: {}
    name: 1.1-8
    referencePolicy:
      type: Source
  - annotations: null
    from:
      kind: DockerImage
      name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:latest
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
